[tool.black]
line-length = 100

[tool.isort]
line_length = 100
lines_after_imports = 2
multi_line_output = 3  # to handle the same way as black
include_trailing_comma = true  # to handle the same way as black
